# Generated by Django 2.2.7 on 2019-11-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='hora',
        ),
    ]
