# Generated by Django 2.2.7 on 2019-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_pedido_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
