# Generated by Django 2.2.7 on 2019-11-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191118_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
    ]
